---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

workspace:
  base: /drone
  path: ffmpeg/src

steps:
- name: build
  image: debian:bullseye
  commands:
  - echo "deb-src http://deb.debian.org/debian bullseye main" >> /etc/apt/sources.list
  - apt-get update
  - apt-get -y build-dep ffmpeg
  - apt-get -y install tree wget
  - wget https://github.com/sigmaris/linux/releases/download/5.5-rkvdec-ayufan-ci/linux-libc-dev_5.5.0-g02f0eaab65e2-sigmaris_arm64.deb
  - dpkg -i linux-libc-dev_5.5.0-g02f0eaab65e2-sigmaris_arm64.deb
  - sed -i -e "s/@@BUILD NUMBER@@/${DRONE_BUILD_NUMBER}/g" debian/changelog
  - sed -i -e "s/@@BUILD TIMESTAMP@@/$(date '+%a, %d %b %Y %H:%M:%S %z')/g" debian/changelog
  - dpkg-buildpackage -us -uc -b --jobs=auto
  - echo "*** Built artifacts ***"
  - ls -l ..
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /drone/ffmpeg/*.deb
    checksum:
    - md5
    - sha1
    - sha256
  when:
    event: tag

trigger:
  ref:
  - refs/heads/rockpkg
  - refs/heads/rockpkg-retry
  - refs/heads/rockpkg-bullseye
  - refs/tags/*
